language: node_js
services:
  - docker

stages:
  - name: docker
    if: tag IS present

jobs:
  include:
    # Build images and push to docker hub commits which are tagged on master.
    - stage: docker
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - GIT_TAG=$(git describe --tags)
      - docker image build -t monitool-api:latest api
      - docker image tag monitool-api romaingilliotte/monitool-api:$GIT_TAG
      - docker image push romaingilliotte/monitool-api:$GIT_TAG
      - docker image tag monitool-api romaingilliotte/monitool-api:latest
      - docker image push romaingilliotte/monitool-api:latest

    - stage: docker
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - GIT_TAG=$(git describe --tags)
      - docker image build -t monitool-frontend:latest frontend
      - docker image tag monitool-frontend romaingilliotte/monitool-frontend:$GIT_TAG
      - docker image push romaingilliotte/monitool-frontend:$GIT_TAG
      - docker image tag monitool-frontend romaingilliotte/monitool-frontend:latest
      - docker image push romaingilliotte/monitool-frontend:latest
