version: "3.6"

services:
  frontend:
    image: node:10-slim
    working_dir: /app
    command: sh -c "yarn && yarn start"
    ports:
      - "8080:8080" # webpack-dev-server
    volumes:
      - ./frontend:/app

  api:
    image: node:10-slim
    working_dir: /app
    command: sh -c "yarn && yarn start"
    ports:
      - "8000:8000" # api
      - "9229:9229" # debugger
    volumes:
      - ./api:/app
    environment:
      MONITOOL_DEBUG: "TRUE"
      MONITOOL_PORT: "8000"
      MONITOOL_JWT_JWKS: "https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_NSicpjtuG/.well-known/jwks.json"
      MONITOOL_COUCHDB_HOST: "couchdb"
      MONITOOL_COUCHDB_PORT: "5984"
      MONITOOL_COUCHDB_DATABUCKET: "monitool"
      MONITOOL_COUCHDB_USER: "admin"
      MONITOOL_COUCHDB_PASS: "admin"

  couchdb:
    image: couchdb:2
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "admin"
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
