version: "3.6"

services:
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    command: --replSet rs0

  redis:
    image: redis
    ports:
      - "6379:6379"

  unoconv:
    image: zrrrzzt/docker-unoconv-webservice
    ports:
      - "8083:3000"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8082:8081"
    environment:
      REDIS_HOST: redis

volumes:
  mongo_data:
