version: "3.6"

services:
  couchdb:
    image: couchdb:2
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "admin"
    volumes:
      - couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
