name: Deploy API
on:
  push:
    tags: ['monitool-api**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: docker_meta
        name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/monitool-api
          tag-match: monitool-api-v(.*)
          tag-match-group: 1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker image pull ${{ secrets.DOCKER_USERNAME }}/monitool-api:latest &&
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/monitool-api:latest monitool_api
          host: monitool.org
          username: eloims
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
