name: Deploy Workers
on:
  push:
    tags: ['monitool-workers**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: docker_meta
        name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/monitool-workers
          tag-match: monitool-workers-v(.*)
          tag-match-group: 1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./workers
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/monitool-workers:latest
          cache-to: type=inline
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker image pull ${{ secrets.DOCKER_USERNAME }}/monitool-workers:latest &&
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/monitool-workers:latest monitool_workers
          host: monitool.org
          username: eloims
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
